 export  const COURSE_LIST_LOADING= 'COURSE_LIST_LOADING';
 export  const COURSE_LIST_SUCCESS= 'COURSE_LIST_SUCCESS';
 export  const COURSE_LIST_ERROR= 'COURSE_LIST_ERROR';

 export  const COURSE_LOADING= 'COURSE_LOADING';
 export  const COURSE_SUCCESS= 'COURSE_SUCCESS';
 export  const COURSE_ERROR= 'COURSE_ERROR';