 export  const FETCH_STUDENT_REQUEST= 'FETCH_STUDENT_REQUEST';
 export  const FETCH_STUDENT_SUCCESS= 'FETCH_STUDENT_SUCCESS';
 export  const FETCH_STUDENT_FAILURE= 'FETCH_STUDENT_FAILURE';

 export  const FETCH_STUDENT_LIST_REQUEST= 'FETCH_STUDENT_LIST_REQUEST';
 export  const FETCH_STUDENT_LIST_SUCCESS= 'FETCH_STUDENT_LIST_SUCCESS';
 export  const FETCH_STUDENT_LIST_FAILURE= 'FETCH_STUDENT_LIST_FAILURE';

 export  const FETCH_STUDENT_COURSE_LIST_REQUEST= 'FETCH_STUDENT_COURSE_LIST_REQUEST';
 export  const FETCH_STUDENT_COURSE_LIST_SUCCESS= 'FETCH_STUDENT_COURSE_LIST_SUCCESS';
 export  const FETCH_STUDENT_COURSE_LIST_FAILURE= 'FETCH_STUDENT_COURSE_LIST_FAILURE';