 export  const FETCH_LECTURER_LIST_REQUEST= 'FETCH_LECTURER_LIST_REQUEST';
 export  const FETCH_LECTURER_LIST_SUCCESS= 'FETCH_LECTURER_LIST_SUCCESS';
 export  const FETCH_LECTURER_LIST_FAILURE= 'FETCH_LECTURER_LIST_FAILURE';

 export  const FETCH_LECTURER_COURSES_REQUEST= 'FETCH_LECTURER_COURSES_REQUEST';
 export  const FETCH_LECTURER_COURSES_SUCCESS= 'FETCH_LECTURER_COURSES_SUCCESS';
 export  const FETCH_LECTURER_COURSES_FAILURE= 'FETCH_LECTURER_COURSES_FAILURE';

 export  const FETCH_LECTURER_REQUEST= 'FETCH_LECTURER_REQUEST';
 export  const FETCH_LECTURER_SUCCESS= 'FETCH_LECTURER_SUCCESS';
 export  const FETCH_LECTURER_FAILURE= 'FETCH_LECTURER_FAILURE';