 export  const PROGRAMME_LIST_LOADING= 'PROGRAMME_LIST_LOADING';
 export  const PROGRAMME_LIST_SUCCESS= 'PROGRAMME_LIST_SUCCESS';
 export  const PROGRAMME_LIST_ERROR= 'PROGRAMME_LIST_ERROR';

 export  const PROGRAMME_LOADING= 'PROGRAMME_LOADING';
 export  const PROGRAMME_SUCCESS= 'PROGRAMME_SUCCESS';
 export  const PROGRAMME_ERROR= 'PROGRAMME_ERROR';