 export  const USER_LIST_LOADING= 'USER_LIST_LOADING';
 export  const USER_LIST_SUCCESS= 'USER_LIST_SUCCESS';
 export  const USER_LIST_ERROR= 'USER_LIST_ERROR';


 export  const USER_LOADING= 'USER_LOADING';
 export  const USER_SUCCESS= 'USER_SUCCESS';
 export  const USER_ERROR= 'USER_ERROR';