 export  const CAMPUS_LIST_LOADING= 'CAMPUS_LIST_LOADING';
 export  const CAMPUS_LIST_SUCCESS= 'CAMPUS_LIST_SUCCESS';
 export  const CAMPUS_LIST_ERROR= 'CAMPUS_LIST_ERROR';

 export  const CAMPUS_LOADING= 'CAMPUS_LOADING';
 export  const CAMPUS_SUCCESS= 'CAMPUS_SUCCESS';
 export  const CAMPUS_ERROR= 'CAMPUS_ERROR';