 export  const SCHOOL_LIST_LOADING= 'SCHOOL_LIST_LOADING';
 export  const SCHOOL_LIST_SUCCESS= 'SCHOOL_LIST_SUCCESS';
 export  const SCHOOL_LIST_ERROR= 'SCHOOL_LIST_ERROR';

 export  const SCHOOL_LOADING= 'SCHOOL_LOADING';
 export  const SCHOOL_SUCCESS= 'SCHOOL_SUCCESS';
 export  const SCHOOL_ERROR= 'SCHOOL_ERROR';